import math
input_values=input("Enter the values of l & b & h in this given order")
list=input_values.split(" ")
L=int(list[0])
B=int(list[1])
H=int(list[-1])
k=(L**2 + B**2 + H**2)
vol=(B**2 * H**2)/math.sqrt(k)
r=((3*vol)/(4*math.pi))**(1/3)
print(f" volume of romboloid={round(vol,3)} \nvalue of K={k}\n radius of sphere ={round(r,3)}")
